### ISSUE TITLE
smg panics when given an nonexistent command

### ISSUE THREAD

**Issue by bfontaine** [jbdalido/smg#4]
```
$ smg hello
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5b0c5]

goroutine 1 [running]:
github.com/jbdalido/smg/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc208096000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/smuggler20150408-53925-1d2o5pz/src/github.com/jbdalido/smg/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:135 +0xbc5
main.main()
	/private/tmp/smuggler20150408-53925-1d2o5pz/smg.go:130 +0xf81

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

$ go version
go version go1.4.2 darwin/amd64
```

**Comment by jbdalido** [comment]
i'll look into it right now
